name: Test Tag Trigger

on:
  push:
    tags: ['v*']

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Print tag info
        run: |
          echo "Tag: ${{ github.ref }}"
          echo "Event: ${{ github.event_name }}"
          echo "SHA: ${{ github.sha }}"